### ISSUE TITLE
Fix GraphSorter

### ISSUE THREAD

**Issue by Eugentis** [spiral/keeper#13]
In case when you are working with Keeper controllers you can met some strange error with message like:
`[ErrorException]
 Undefined index: index
in /var/www/vendor/spiral/helpers/src/GraphSorter.php:80`

It looks as a big problem but in reality it is simple error with annotated controller when you define not existing parent for sitemap:
`@Keeper\Sitemap\View(title="Create Client", parent="index")`

In described example controller has no action `index` and it is a root of the issue.

**Comment by vvval** [comment]
@Eugentis the issue is mostly fixed. The error will be skipped for 99% sure, but it will act like the whole `parent` attribute is empty. Feel free to add logging in case of unknown `parent` is presented in the SitemapBuilder (look for `knownParent`) as a PR
