### ISSUE TITLE
Ability to work with keeper routes via RouterInterface

### ISSUE THREAD

**Issue by EvgenyBarinov** [spiral/keeper#7]
Now I can work with keeper routes only with RouteRegistry. It will be more comfortable to work with all routes via common interface

**Comment by vvval** [comment]
@EvgenyBarinov done, use new helper https://github.com/spiral/keeper/blob/c9c9cde249201ffdd3d8b2cacb44b24c40095541/src/Helper/RouteBuilder.php#L21
> It requires keeper namespace name as a 1st argument
